### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by oantot** [Oth3r/DirectionHUD#3]
hey there 

sorry for the in convince but there is no config menu for it and it doesnt work on my computer

best of luck

**Comment by Oth3r** [comment]
To edit the config in game on the client, you need the mods Yet Another Config Lib and Mod Menu installed
I also need to know where you are trying to use the mod, that will help solve the not working issue.

**Comment by Oth3r** [comment]
please provide details about this issue to continue! 👍
